version: '3.6'
services:
  orion1:
    build:
      context: build/orion
      args: 
        - ORION_VERSION=${ORION_VERSION}
    image: pegasyseng/orion:${ORION_VERSION}
    command: [
      "${ORION_NODE_DATA_DIR}orion.conf"
    ]
    ports:
      - 33001:9001
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.11'
    volumes:
      - ${PWD}/data/orion1:${ORION_NODE_DATA_DIR}
  orion2:
    image: pegasyseng/orion:${ORION_VERSION}
    command: [
      "${ORION_NODE_DATA_DIR}orion.conf"
    ]
    ports:
      - 33002:9001
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.12'
    volumes:
      - ${PWD}/data/orion2:${ORION_NODE_DATA_DIR}

  orion3:
    image: pegasyseng/orion:${ORION_VERSION}
    command: [
      "${ORION_NODE_DATA_DIR}orion.conf"
    ]
    ports:
      - 33003:9001
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.13'
    volumes:
      - ${PWD}/data/orion3:${ORION_NODE_DATA_DIR}

  orion4:
    image: pegasyseng/orion:${ORION_VERSION}
    command: [
      "${ORION_NODE_DATA_DIR}orion.conf"
    ]
    ports:
      - 33004:9001
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.14'
    volumes:
      - ${PWD}/data/orion4:${ORION_NODE_DATA_DIR}

  orion5:
    image: pegasyseng/orion:${ORION_VERSION}
    command: [
      "${ORION_NODE_DATA_DIR}orion.conf"
    ]
    ports:
      - 33005:9001
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.15'
    volumes:
      - ${PWD}/data/orion5:${ORION_NODE_DATA_DIR}

  node1:
    depends_on:
      - orion1
    image: pegasyseng/pantheon:${PANTHEON_VERSION}
    entrypoint: [
      "/opt/pantheon/bin/pantheon",
    ]
    command: [
      "--data-path=${PANTHEON_NODE_DATA_DIR}",
      "--genesis-file=${PANTHEON_SHARED_FILES_DIR}genesis.json",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=${PANTHEON_RPC_HTTP_APIS}",
      "--host-whitelist=*",
      "--bootnodes",
      "--min-gas-price=0",
      "--privacy-enabled=true",
      "--privacy-url=http://172.21.0.11:9002",
      "--privacy-public-key-file=${ORION_NODE_DATA_DIR}orion.pub"
    ]
    ports:
      - 22001:8545
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.21'
    volumes:
      - ${PWD}/data/shared:${PANTHEON_SHARED_FILES_DIR}
      - ${PWD}/data/node1:${PANTHEON_NODE_DATA_DIR}
      - ${PWD}/data/orion1:${ORION_NODE_DATA_DIR}

  node2:
    depends_on:
      - node1
      - orion2
    image: pegasyseng/pantheon:${PANTHEON_VERSION}
    entrypoint: [
      "/opt/pantheon/bin/pantheon",
    ]
    command: [
      "--data-path=${PANTHEON_NODE_DATA_DIR}",
      "--genesis-file=${PANTHEON_SHARED_FILES_DIR}genesis.json",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=${PANTHEON_RPC_HTTP_APIS}",
      "--host-whitelist=*",
      "--bootnodes=${PANTHEON_BOOTNODES}",
      "--min-gas-price=0",
      "--privacy-enabled=true",
      "--privacy-url=http://172.21.0.12:9002",
      "--privacy-public-key-file=${ORION_NODE_DATA_DIR}orion.pub"
    ]
    ports:
      - 22002:8545
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.22'
    volumes:
      - ${PWD}/data/shared:${PANTHEON_SHARED_FILES_DIR}
      - ${PWD}/data/node2:${PANTHEON_NODE_DATA_DIR}
      - ${PWD}/data/orion2:${ORION_NODE_DATA_DIR}

  node3:
    depends_on:
      - node1
      - orion3
    image: pegasyseng/pantheon:${PANTHEON_VERSION}
    entrypoint: [
      "/opt/pantheon/bin/pantheon",
    ]
    command: [
      "--data-path=${PANTHEON_NODE_DATA_DIR}",
      "--genesis-file=${PANTHEON_SHARED_FILES_DIR}genesis.json",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=${PANTHEON_RPC_HTTP_APIS}",
      "--host-whitelist=*",
      "--bootnodes=${PANTHEON_BOOTNODES}",
      "--min-gas-price=0",
      "--privacy-enabled=true",
      "--privacy-url=http://172.21.0.13:9002",
      "--privacy-public-key-file=${ORION_NODE_DATA_DIR}orion.pub"
    ]
    ports:
      - 22003:8545
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.23'
    volumes:
      - ${PWD}/data/shared:${PANTHEON_SHARED_FILES_DIR}
      - ${PWD}/data/node3:${PANTHEON_NODE_DATA_DIR}
      - ${PWD}/data/orion3:${ORION_NODE_DATA_DIR}

  node4:
    depends_on:
      - node1
      - orion4
    image: pegasyseng/pantheon:${PANTHEON_VERSION}
    entrypoint: [
      "/opt/pantheon/bin/pantheon",
    ]
    command: [
      "--data-path=${PANTHEON_NODE_DATA_DIR}",
      "--genesis-file=${PANTHEON_SHARED_FILES_DIR}genesis.json",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=${PANTHEON_RPC_HTTP_APIS}",
      "--host-whitelist=*",
      "--bootnodes=${PANTHEON_BOOTNODES}",
      "--min-gas-price=0",
      "--privacy-enabled=true",
      "--privacy-url=http://172.21.0.14:9002",
      "--privacy-public-key-file=${ORION_NODE_DATA_DIR}orion.pub"
    ]
    ports:
      - 22004:8545
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.24'
    volumes:
      - ${PWD}/data/shared:${PANTHEON_SHARED_FILES_DIR}
      - ${PWD}/data/node4:${PANTHEON_NODE_DATA_DIR}
      - ${PWD}/data/orion4:${ORION_NODE_DATA_DIR}

  node5:
    depends_on:
      - node1
      - orion5
    image: pegasyseng/pantheon:${PANTHEON_VERSION}
    entrypoint: [
      "/opt/pantheon/bin/pantheon",
    ]
    command: [
      "--data-path=${PANTHEON_NODE_DATA_DIR}",
      "--genesis-file=${PANTHEON_SHARED_FILES_DIR}genesis.json",
      "--rpc-http-enabled=true",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-cors-origins=all",
      "--rpc-http-api=${PANTHEON_RPC_HTTP_APIS}",
      "--host-whitelist=*",
      "--bootnodes=${PANTHEON_BOOTNODES}",
      "--min-gas-price=0",
      "--miner-enabled",
      "--miner-coinbase=${PANTHEON_COINBASE}",
      "--privacy-enabled=true",
      "--privacy-url=http://172.21.0.15:9002",
      "--privacy-public-key-file=${ORION_NODE_DATA_DIR}orion.pub"
    ]
    ports:
      - 22005:8545
    networks:
      pantheon_net:
        ipv4_address: '172.21.0.25'
    volumes:
      - ${PWD}/data/shared:${PANTHEON_SHARED_FILES_DIR}
      - ${PWD}/data/node5:${PANTHEON_NODE_DATA_DIR}
      - ${PWD}/data/orion5:${ORION_NODE_DATA_DIR}

networks:
  pantheon_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.21.0.0/16
