/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractOptions, Options } from "web3-eth-contract";
import { Block } from "web3-eth";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { Callback, TransactionObject } from "./types";

export class PassportLogic extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    getTxDataBlockNumber(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      blockNumber: string;
      0: boolean;
      1: string;
    }>;

    isAllowedFactProvider(_address: string): TransactionObject<boolean>;

    getIPFSHash(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: string;
      0: boolean;
      1: string;
    }>;

    getBytes(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: (string)[];
      0: boolean;
      1: (string)[];
    }>;

    getUint(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: string;
      0: boolean;
      1: string;
    }>;

    getAddress(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: string;
      0: boolean;
      1: string;
    }>;

    isFactProviderInWhitelist(_address: string): TransactionObject<boolean>;

    getInt(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: string;
      0: boolean;
      1: string;
    }>;

    getBool(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: boolean;
      0: boolean;
      1: boolean;
    }>;

    getString(
      _factProvider: string,
      _key: string | number[]
    ): TransactionObject<{
      success: boolean;
      value: string;
      0: boolean;
      1: string;
    }>;

    deleteAddress(_key: string | number[]): TransactionObject<void>;

    deleteIPFSHash(_key: string | number[]): TransactionObject<void>;

    setWhitelistOnlyPermission(
      _onlyWhitelist: boolean
    ): TransactionObject<void>;

    deleteBool(_key: string | number[]): TransactionObject<void>;

    setBytes(
      _key: string | number[],
      _value: (string | number[])[]
    ): TransactionObject<void>;

    setInt(
      _key: string | number[],
      _value: number | string
    ): TransactionObject<void>;

    claimOwnership(): TransactionObject<void>;

    setTxDataBlockNumber(
      _key: string | number[],
      _data: (string | number[])[]
    ): TransactionObject<void>;

    deleteBytes(_key: string | number[]): TransactionObject<void>;

    setIPFSHash(
      _key: string | number[],
      _value: string
    ): TransactionObject<void>;

    removeFactProviderFromWhitelist(_address: string): TransactionObject<void>;

    setString(_key: string | number[], _value: string): TransactionObject<void>;

    renounceOwnership(): TransactionObject<void>;

    deleteInt(_key: string | number[]): TransactionObject<void>;

    deleteTxDataBlockNumber(_key: string | number[]): TransactionObject<void>;

    setBool(_key: string | number[], _value: boolean): TransactionObject<void>;

    addFactProviderToWhitelist(_address: string): TransactionObject<void>;

    setAddress(
      _key: string | number[],
      _value: string
    ): TransactionObject<void>;

    setUint(
      _key: string | number[],
      _value: number | string
    ): TransactionObject<void>;

    deleteUint(_key: string | number[]): TransactionObject<void>;

    transferOwnership(newOwner: string): TransactionObject<void>;

    deleteString(_key: string | number[]): TransactionObject<void>;

    isWhitelistOnlyPermissionSet(): TransactionObject<boolean>;
    owner(): TransactionObject<string>;
    pendingOwner(): TransactionObject<string>;
  };
  events: {
    IPFSHashUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    IPFSHashDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    TxDataUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    TxDataDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    BytesUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    BytesDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    StringUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    StringDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    BoolUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    BoolDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    IntUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    IntDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    UintUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    UintDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    AddressUpdated(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    AddressDeleted(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    WhitelistOnlyPermissionSet(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    WhitelistFactProviderAdded(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    WhitelistFactProviderRemoved(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    OwnershipRenounced(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    OwnershipTransferred(
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
